{{- if .Values.serviceAccount.role.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.serviceAccount.role.name }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
{{- end }}

{{- if .Values.serviceAccount.clusterRole.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccount.clusterRole.name }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
{{- end }}

{{- if .Values.serviceAccount.roleBinding.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceAccount.roleBinding.name }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ default (include "lightstep.serviceAccountName" .) .Values.serviceAccount.roleBinding.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ default .Values.serviceAccount.role.name .Values.serviceAccount.roleBinding.roleRefName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- if .Values.serviceAccount.clusterRoleBinding.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceAccount.clusterRoleBinding.name }}
subjects:
- kind: ServiceAccount
  name: {{ default (include "lightstep.serviceAccountName" .) .Values.serviceAccount.clusterRoleBinding.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ default .Values.serviceAccount.clusterRole.name .Values.serviceAccount.clusterRoleBinding.roleRefName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
