apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.annotations }}
  annotations: {{ .Values.service.annotations | toYaml | nindent 4 }}
  {{- end }}
  name: {{ include "lightstep.fullname" . }}
  labels:
    {{- include "lightstep.labels" . | nindent 4 }}
spec:
{{ if .Values.service.grpc }}
  clusterIP: None
{{ else }}
  type: {{ .Values.service.type }}
{{ end }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
    - name: grpc-insecure
      port: {{ .Values.service.grpcinsecure }}
      targetPort: {{ .Values.service.grpcinsecure }}
  selector:
    {{- include "lightstep.selectorLabels" . | nindent 4 }}