apiVersion: v1
name: lightstep
version: 2.0.2
appVersion: "2021-03-22_13-16-05Z"
description: Lightstep microsatellite to collect telemetry data.
home: https://lightstep.com/
icon: https://go.lightstep.com/rs/260-KGM-472/images/logo-medium-color-400x100.jpg
engine: gotpl
